### ISSUE TITLE
3D secure

### ISSUE THREAD

**Issue by mihaiappwholesale** [Worldpay/worldpay-magento#13]
I managed to install it properly on dev and live but currently I can't work the 3D secure because it's putting in worldpay dashboard Pre-authorized and it's not appearing in magento at all.
I've put the webhook and it's returning 200 so it's working.

Please let me know if I need to add the success url on worldpay dashboard or what else I need to do to make it work. Thank you

**Comment by franksmule** [comment]
Do you have a link to a test environment and I can have a look?

**Comment by mihaiappwholesale** [comment]
sandbox.mrcentralheating.co.uk <http://sandbox.mrcentralheating.co.uk/>

Please let me know if you need anything else.


Mihai Mocanu
Senior Web Developer
07427 668371
0208 536 6024
mihai@appwholesale.co.uk <mailto:mihai@appwholesale.co.uk>

**Comment by franksmule** [comment]
Could you edit /app/design/frontend/base/default/template/worldpay/urls.phtml and replace line 2 with this..

    window.wp_threeDSCompleteURL = '<?php echo Mage::getUrl('worldpay/threeDS/checkout', array('_secure'=>true)); ?>';

This should force the URL to be https.

**Comment by mihaiappwholesale** [comment]
nope, still no luck... the "place order" button it's not working it's sending something

+ I am getting in the console

Blocked loading mixed active content "http://sandbox.mrcentralheating.co.uk/worldpay/threeDS/"1 worldpay.js:187:0

**Comment by mihaiappwholesale** [comment]
hi guys? any luck with this? please let me know as it is important we have it live

**Comment by mihaiappwholesale** [comment]
I managed to fix it.
I had to edit:
app/code/community/Worldpay/Payments/Model/PaymentMethods/Abstract.php
and 
/var/www/sandbox.mrcentralheating.co.uk/httpdocs/app/code/community/Worldpay/Payments/controllers/ThreeDSController.php

to make the unsecure URLs secure

not the test it's working but the live it's not, 3D secure it's pulling an iframe but that iframe is empty and then it's keep refreshing... can you please help with this?

**Comment by franksmule** [comment]
1.7.0 reimplements 3D Secure
