### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by netzkollektiv** [Worldpay/worldpay-magento#18]
Is this the official plugin page of Worldpay? 
Is this extension still maintained? 

The most recent version is for Magento 1.8 which is more than two years old.

**Comment by ao** [comment]
@netzkollektiv This is still maintained and is for Magento1. The newer implementations are in Magento2 over at https://github.com/Worldpay/worldpay-magento2

**Comment by netzkollektiv** [comment]
Thank you for the quick reply! Then I'll open an issue ;)

**Comment by ao** [comment]
np
