### ISSUE TITLE
Incorrect file case

### ISSUE THREAD

**Issue by Demoli** [Worldpay/worldpay-magento#21]
File `app/code/community/Worldpay/Payments/lib/lib/worldpay.php` has a lowercase filename, but is included in file `app/code/community/Worldpay/Payments/lib/init.php` with a capitalised filename `Worldpay.php`

This means the module crashes as soon as it is used on a case sensitive file system.

**Comment by ao** [comment]
HI @Demoli 
This has been resolved, please pull or use version 1.8.1
