### ISSUE TITLE
Dummy Payment Model missing

### ISSUE THREAD

**Issue by jamesskywire** [Worldpay/worldpay-magento#24]
Because the following file has been removed from the latest release you also need to remove it from the config to avoid an error from the autoloader on the checkout page.

- **File**: worldpay-magento/app/code/community/Worldpay/Payments/etc/config.xml
- **Lines**: 122-132

Thanks,
James

**Comment by denizengin** [comment]
Thanks James.

**Comment by jamesskywire** [comment]
Great stuff thanks very much.
