### ISSUE TITLE
Secure URL

### ISSUE THREAD

**Issue by peterhough** [Worldpay/worldpay-magento#8]
Consider altering occurances of `Mage::getUrl` to force a secure URL.
For example: `Mage::getUrl('checkout/multishipping/backtobilling', array('_secure'=>true))`

**Comment by ramijosef** [comment]
Hi Peter,

Thank you for reaching out.

We are constantly updating our libraries, I shall get this feedback passed to our product team to analyse and act on if necessary.

Any questions, let me know.

Regards,

Rami

**Comment by franksmule** [comment]
Changed in 1.7.0
